version: '3.9'

services:
  db:
    image: postgres:15.2
    container_name: utsubo-site-postgres
    volumes:
      - 'postgres_volume:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  api:
    image: utsubo-site-api
    container_name: utsubo-site-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/myapp'
    environment:
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    tty: true
    stdin_open: true
    depends_on:
      - db

volumes:
  postgres_volume:
