# fly.toml app configuration file generated for utsubo-site-api on 2023-05-06T13:59:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "utsubo-site-api"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
